global using JwtExample.Microservices.AuthService.Domain.Core.Models;
global using JwtExample.Microservices.AuthService.Domain.Core.Models.Configuration;
global using JwtExample.Microservices.AuthService.Domain.Core.Models.Requests;
global using JwtExample.Microservices.AuthService.Domain.Core.Models.Responses;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;