global using JwtExample.Microservices.AuthService.Domain.Core.Models.Requests;
global using JwtExample.Microservices.AuthService.Domain.Core.Models.Responses;
global using JwtExample.Microservices.AuthService.Domain.Handlers;
global using JwtExample.Microservices.AuthService.Infra.IoC;
global using JwtExample.Microservices.AuthService.Infra.IoC.MediatR;
global using JwtExample.Microservices.AuthService.Presentation.Configurations;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Serilog.Events;